### ISSUE TITLE
Tous niveaux - MARKDOWN : problème d'affichage

### ISSUE THREAD

**Issue by Alexandre-S1** [Francoralite/francoralite#102]
Tous niveaux - MARKDOWN:
- le saut de ligne ou d'autres fonctionnalités comme le tableau ne s'affichent pas en consultation : c'est le code markdown qui apparaît.

**Comment by mnauge** [comment]
je viens de faire un test dans le champs description de cet item :
https://app.preprod.francoralite.net/item/9

Le code markdown ne s'affiche plus, donc problème plutôt résolu. 
Par contre le rendu du tableau n'est pas beau. je tag ça en ergo.
