### ISSUE TITLE
[ITEM] Retirer Fonction+Danse du pavé Témoignage

### ISSUE THREAD

**Issue by Alexandre-S1** [Francoralite/francoralite#113]
ITEM : Les champs Fonction et Danse ne sont pas rattachés au pavé Témoignage.

En mode création/édition, si possible, faire remonter ces 2 champs tout en haut de l'onglet Description.

**Comment by Alexandre-S1** [comment]
Bien vu @mnauge il y a erreur de ma part. 

@lluc merci d'avoir bien corrigé dans le sens que j'avais demandé, mais ma demande n'était pas exacte, toutes mes excuses.

Idéalement ces 2 champs (Fonction et Danse) devraient être dans le pavé "Genres" (cf. maquettes), sous le champ "Genre du conte"...

**Comment by mnauge** [comment]
Est-il possible d'atteindre l'objectif idéal préconisé par Alexandre décrit ci-dessus ?

**Comment by lluc** [comment]
@mnauge A priori, oui.

**Comment by lluc** [comment]
Résolu dans l'issue #149 commit 231fae35b0168a8a81298050eb44669c4d08f54e
