### ISSUE TITLE
Marqueurs - Bug en édition

### ISSUE THREAD

**Issue by Alexandre-S1** [Francoralite/francoralite#116]
Choix d'un marqueur > clic sur Edit > éventuellement modifier > clic sur OK > bulle d'erreur

ERROR: Failed to save
The server responded witha status of 500 (Internal Server Error)

Details (request responseText):
{"error": {"message": "OtherError: Internal Server Error", "code": 500, "data": null, "name": "OtherError"}, "jsonrpc": "1.0", "id": "jsonrpc", "result": null}

**Comment by Alexandre-S1** [comment]
C'est assez problématique car on ne peut pas corriger une erreur.

**Comment by lluc** [comment]
Le composant TimeSide n'est plus utilisé.
