### ISSUE TITLE
Marqueurs > problème affichage en édition

### ISSUE THREAD

**Issue by Alexandre-S1** [Francoralite/francoralite#120]
les bulles des marqueurs sont ratatinées, il faut les agrandir manuellement pour voir ce qu'il y a ou pas dedans. Cf image en pj.
![2](https://user-images.githubusercontent.com/58727595/86341597-cbc33a00-bc56-11ea-86b4-c0695436b8e1.jpeg)
![1](https://user-images.githubusercontent.com/58727595/86341603-cd8cfd80-bc56-11ea-9170-e92658ce57f3.jpeg)

**Comment by mnauge** [comment]
Composant timeside supprimé. Nous conseillons de réaliser l'édition de la transcription de la parole alignée au son en local via praat/transcriber ou tout autre outils de création de sous-titre.
