### ISSUE TITLE
Problème avec fenêtre markdown

### ISSUE THREAD

**Issue by Alexandre-S1** [Francoralite/francoralite#121]
Il est parfois impossible de remonter "en haut" du champ markdown, impossible de voir les premières lignes. Comme si cela glissait derrière la barre d'outils de mise en page. Cf capture écran.

Problématique au-delà de l'aspect esthétique, puisqu'il est difficile de vérifier/corriger la saisie.

Ici au niveau ITEM / onglet Texte / Champ Paroles, à voir si le problème est étendu à tous les champs similaires.
![Sans titre](https://user-images.githubusercontent.com/58727595/86455321-bc102800-bd20-11ea-9830-7eecb2344456.jpeg)

**Comment by lluc** [comment]
Exemple récent : https://app.beta.francoralite.net/item/edit/22

**Comment by lluc** [comment]
:information_source: Penser à utiliser les flêches *haut* et *bas* du clavier pour se déplacer dans la zone de saisie.

**Comment by mnauge** [comment]
OK. ça marche avec les flèches haut/bas
