### ISSUE TITLE
FONDS : pavé période reste vide

### ISSUE THREAD

**Issue by Alexandre-S1** [Francoralite/francoralite#129]
Devrait concaténer les Années d'enregistrement et la Durée totale disponible

**Comment by lluc** [comment]
:warning: Actuellement les *durée totale disponible* ne sont pas calculées.

**Comment by mnauge** [comment]
ok, pour les années !
Je ne clôture pas car "Actuellement les durée totale disponible ne sont pas calculées." ;-)

**Comment by lluc** [comment]
**TODO** : Effectuer un calcul du temps total tel que la fonction *duration* pour les Missions.

**Comment by mnauge** [comment]
Parfait. Merci.
