### ISSUE TITLE
BUREAU ?

### ISSUE THREAD

**Issue by Alexandre-S1** [Francoralite/francoralite#132]
Est-il prévu de remettre en place l'onglet Bureau (un espace personnel, avec des listes de lectures...) ?
Actuellement, l'onglet ne renvoie à rien.

**Comment by mnauge** [comment]
Pas planifié de budget pour l'ajout d'un "panier d'item/liste de lecture/espace personnel". S'orienter vers des solutions externes, généralistes et collaborative type zotero.
