### ISSUE TITLE
ENQUETE : autocomplétion LIEU

### ISSUE THREAD

**Issue by Alexandre-S1** [Francoralite/francoralite#135]
Dans le champ LIEU au niveau ENQUETE, l'autocomplétion ne va pas chercher dans le champ "NOM" de la fiche-lieu. Il faudrait que ce soit le cas car ce champ NOM est parfois plus pertinent que les données de géolocalisation automatisées.

**Comment by lluc** [comment]
@mnauge a priori, c'est déjà le cas.
https://github.com/Francoralite/francoralite/blob/570e24dee0cd10903ba1b2d8bf258069af439166/francoralite/apps/francoralite_api/views/location_gis.py#L26
