### ISSUE TITLE
ENQUETE > LIEU > la liste coupe les mots

### ISSUE THREAD

**Issue by Alexandre-S1** [Francoralite/francoralite#136]
Dans le champ en autocomplétion, le fait de survoler un lieu "coupe" la moitié de ses informations (voir image)

![Sans titre](https://user-images.githubusercontent.com/58727595/87069427-728b7580-c217-11ea-9dbc-93943862f38d.jpeg)

**Comment by lluc** [comment]
@mnauge cela ne semble plus être le cas.
