### ISSUE TITLE
Créer un ITEM : les fichiers audio accentués sont rejetés

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#139]
Quand je créé un item en incluant un fichier audio avec un é (accent) dans le nom, la page est réinitialisée.

#### Comment reproduire le problème :
- créer un item
- écrire le titre : `LE COUTEAU VOLÉ Le temps que j'étais jeune enfant`
- écrire la côte : `UPOI_CHB_0001_0001_001`
- joindre le fichier : `0001-A-00054 C 100 LE COUTEAU VOLÉ Le temps que j'étais jeune enfant Joseph T. Larade (38) Chéticamp, Comté d'. 1957-08-05Inverness, N.-É`
- enregistrer

#### Effet observé : 
- la page est réinitialisée : toutes les données entrées sont effacées et l'item n'est pas créé

#### Effet attendu : 
- l'item est créé 
ou 
- les données sont conservées et un message d'erreur est affiché

**Comment by lluc** [comment]
@Marion-L1  Effectivement, pour le  moment, il vaut mieux saisir des noms de fichiers sans accents (voir sans espaces ou ponctuations ...)
@mnauge je transfère ce ticket dans le tableau "ergonomie" afin que la prochaine version intègre un contrôle et une conversion automatique de nom de fichier

**Comment by lluc** [comment]
Le sérialiseur de *item* convertit maintenant les noms de fichiers dans un format correct ( sans accents, etc ... )

**Comment by mnauge** [comment]
testé/validé avec un fichier nommé "aéb c è.mp3"  qui semble être renommé en aeb_c_e.mp3
