### ISSUE TITLE
ITEM > Description > champs : pas d'apparition de la liste des possibilités 

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#143]
Quand on clique sur les différentes cases sous Fonction(s) ou autre, afin d'obtenir les options possibles, un message "sorry, no matching options" s'affiche. Mais à partir du moment où on inscrit une lettre les options sont accessibles.
Cela est valable pour plusieurs cases de la page.

**Comment reproduire le problème :**
- Aller sur l'item : LE COUTEAU VOLÉ Le temps que j'étais jeune enfant
- Éditer l'item
- Aller sur l'onglet Description
- Cliquer sur la case sous Fonction(s)

**Effet observé :**
- Un message "Sorry, no matching options" apparaît
- Les options apparaissent si on inscrit n'importe quelle lettre

**Effet attendu :**
- Les options sont directement affichées lorsqu'on clique sur la case

**Comment by lluc** [comment]
@Marion-L1 La plupart de ces champs fonctionne ainsi : cela évite que toutes les possibilités ne soient stockées à chaque chargement de page. Cela risquerait de provoquer tes temps de chargement relativement longs une fois que la base de données comportera de nombreux enregistrements.  
Ceci dit, il peut y avoir une modification de l'ergonomie de saisie.  
A voir pour la prochaine version.

**Comment by lluc** [comment]
La sélection se fait désormais par une auto-complétion dans une liste déroulante.
