### ISSUE TITLE
FONDS > Manque du champ "Type d'accès"

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#147]
Dans l'onglet `Fonds`, il manque le champ "Type d'accès" prévu dans la maquette avant `Médias associés`.
Termes possibles dans le menu déroulant :
      Consultation sur demande
      Consultation restreinte
      Accès partiel aux items
      Consultation libre

**Comment by lluc** [comment]
@mnauge @Marion-L1 :question: C'est à discuter, car, à ce jour, ce champ ne figure pas dans le modèle de données *Fonds*.

**Comment by mnauge** [comment]
cf. issue #310

**Comment by lluc** [comment]
@mnauge En fait ce champ est présent dans la table Mission sous la dénomination `public_access`.
