### ISSUE TITLE
ENQUÊTE > Lieu : mauvaise redirection 

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#150]
En mode saisie, lorsque l'on rentre un lieu, l'efface et en rentre un autre, on est redirigé vers la page de l'ensemble des enquêtes lors de l'enregistrement.

**Comment reproduire l'erreur :** 
- Aller sur l'enquête `Enquête 1`
- Éditer l'enquête
- Rentrer le lieu Cherves
- L'effacer et rentrer le lieu Québec (agglomération)
- Enregistrer

**Effet obtenu :**
- Redirection vers la page listant l'ensemble des enquêtes

**Effet souhaité :**
- Redirection vers la page Enquête 1

**Comment by lluc** [comment]
@mnauge @Marion-L1 :warning:   Je ne suis pas arrivé à reproduire l'erreur sur ma machine de développement.  
:thinking: Suite à une modification d'un lieu, je reviens bien sur la fiche de l'enquête.

**Comment by lluc** [comment]
@mnauge à re-vérifier lorsque les enquêtes seront de nouveau accessible sur le serveur *beta*.

**Comment by lluc** [comment]
@mnauge vérifié.

**Comment by mnauge** [comment]
résolu :-)
