### ISSUE TITLE
ITEM > Bug lors d'un enregistrement de fichier -> trop lourd ?

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#151]
**Comment reproduire :**
- remplir tous les champs correspondant à un témoignage avec chanson, beaucoup de citation de noms de personnes, lieux et période
- ajouter le son : fichier ATP_1969.33.5.mp3 : 31 min 38 / 45,6 Mo

**Effet obtenu :**
- message d'erreur 502
- le fichier est tout de même enregistré mais : 
-> ou bien toutes les informations sont enregistrée mais le fichier son est de 7 min 31
-> ou bien le fichier son est entier mais une partie des informations a disparu (notamment nom enquêteurs et informateurs)

**Comment by mnauge** [comment]
@lluc c'est bon ça fonctionne.
