### ISSUE TITLE
ITEM > Voix/Instrument > Pas suffisamment de visibilité pour le choix de la voix/instrument

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#152]
**Comment reproduire l'erreur :**
- Aller sur UPOI_ATP_0001_0001_006 
- Éditer l'Item et aller sur l'onglet Voix/Instruments
- Essayer de rajouter l'information préalablement remplie : 1 Voix d'homme - musicien : Charles Aubrière - chanté

**Effet obtenu :**
- la nature de la voix n'est pas indiquée dans les choix proposés
- il n'est pas possible de savoir quel choix réaliser dans les propositions

**Effet souhaité :**
- la nature de la voix est mentionnée dans l'appelation

**Comment by mnauge** [comment]
Je n'y arrive pas, mais je n'ai peut-être pas bien compris. @Marion-L1, peux-tu te rendre ici https://app.beta.francoralite.net, te connecter, te rendre ici : https://app.beta.francoralite.net/item/edit/34
puis tenter ce que tu as demandé pour nous dire si le problème persiste ? 
Merci :-)

**Comment by mnauge** [comment]
@lluc peux-tu essayer de ton côté sur la version beta stp ? :-)

**Comment by Marion-L1** [comment]
Je viens d'essayer, mais le fait de valider après avoir ajouté une information dans "Voix/instrument" puis Voix/instrument me redirige automatiquement cers cette page-ci.
De plus, il n'y a plus d'autocomplétion pour la voix d'homme parlée de Charles Aubrière, comme auparavent.

**Comment by mnauge** [comment]
@lluc je ne trouve pas de commit après le retour de Marion, je suppose que vous n'avez pas résolu ça ?

**Comment by mnauge** [comment]
ça me semble bon. @Marion-L1 peux-tu confirmer que c'est bien ce que tu attendais ?

**Comment by Marion-L1** [comment]
On peut en effet avoir plus de visibilité...MAIS :
- à l'affichage, on perd le nom de l'informateur/musicien
- en mode édition il y a uniquement un informateur louisianais possible, quelque soit l'item que l'on souhaite modifier. Le fait d'avoir cliqué dessus une fois modifie les information de l'onglet général (enquête, données géographiques...) 
Cf UPOI_ATP_0001_0002_001 que je viens de modifier sans le vouloir
