### ISSUE TITLE
PERSONNES > Informateurs : impossibilité de créer une nouvelle fiche

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#154]
**Comment reproduire le problème :**
- Aller sur PERSONNE > Informateur > Ajouter
- Renseigner les champs : Nom : Aubrière / Civilité : Mme / Rôle : Informateur / Biographie : Mme est la femme de Charles Aubrière

**Effet obtenu :**
- 502 Bad Gateway

**Effet souhaité :**
- la fiche est créée

**Comment by Marion-L1** [comment]
La fiche se créé quand il y a un prénom. Il faut donc savoir qu'il faut rajouter un Mme ou M. dans le champ prénom.
Ca serait bien de soit juste rajouter une étoile rouge et un message d'erreur, soit offrir la possibilité qu'il n'y ait pas de prénom mais que la civilité s'affiche devant le nom dans ces cas là.

**Comment by lluc** [comment]
```
Bad Request: /api/authority
app_1            | Internal Server Error: /authority/add
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
app_1            |     response = get_response(request)
app_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
app_1            |     response = self.process_exception_by_middleware(e, request)
app_1            |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
app_1            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1            |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
app_1            |     return self.dispatch(request, *args, **kwargs)
app_1            |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
app_1            |     return handler(request, *args, **kwargs)
app_1            |   File "/srv/app/francoralite/apps/francoralite_front/views/personne_add.py", line 19, in post
app_1            |     return tools.post('authority', PersonneForm, request, *args, **kwargs)
app_1            |   File "/srv/app/francoralite/apps/francoralite_front/tools.py", line 102, in post
app_1            |     entity=entity)
app_1            |   File "/srv/app/francoralite/apps/francoralite_front/tools.py", line 148, in post_api
app_1            |     raise Exception(HTTP_ERRORS[response.status_code])
app_1            | Exception: 01_400

```

**Comment by mnauge** [comment]
Si je comprends bien ce que dit @Marion-L1 , c'est qu'elle n'arrivait pas à créer une personne si elle n'avait pas connaissance de son prénom. Donc pour réussir à créer une personne dans ce contexte, elle a du trouver un peu par miracle/tâtonnement qu'il fallait qu'elle ajoute un mot bouche trou du genre M ou Mme dans le champs prénom pour que ça passe. Je pense que l'idéal est d'autoriser dans le prénom (ou le nom) une valeur du genre "inconnu" ?!

**Comment by lluc** [comment]
@mnauge Il faut que le champ *prénom* contienne quelque chose. Effectivement, ce peut être M ou Mme, ou même, carrément, un tiret ou un point.

**Comment by mnauge** [comment]
j'ai réussi à créer un nouvel informateur, et j'ai reçu une information de prénom obligatoire.
