### ISSUE TITLE
INSTITUTION > affichage des fonds de toutes les institutions

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#155]
**Comment reproduire le problème :**
- sur le portail, cliquer sur l'onglet Institutions
- choisir Université de Moncton (supprimé depuis)

**Effet obtenu :**
- apparaissent toutes les cotes et descriptions des fonds de l'Université de Poitiers

**Effet souhaité :**
- Affichage des fonds uniquement de l'institution choisie

**Comment by mnauge** [comment]
Il n'y a plus ce problème.
