### ISSUE TITLE
ENQUETE > ONGLET ITEM > Classement par ordre alphabétique/numérique pour les COTES par défaut

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#157]
Actuellement le classement par défaut se fait au niveau des titres.

**Pour reproduire :**
- Aller sur : `Enquête : Témoignage de M. Charles Aubrière - La Biroire, île d'Oléron, septembre 1969` 
- Onglet Items
- Les items sont classés par ordre alphabétique de titre

**Effet demandé :**
- Les items sont classés par ordre alpha-numérique de Cotes

**Comment by mnauge** [comment]
problème bien résolu.
