### ISSUE TITLE
PERSONNES > Fiche personne > Accès aux Items d'une personne par sa fiche personnelle

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#160]
**Comment reproduire :**
- Onglet `Personnes`
- Informateurs > Charles Aubrière

**Effet obtenu :**
- Affichage des information entrées sur cette personne

**Effet souhaité :**
- Accès aux items dans lesquels intervient cet informateur

**Comment by mnauge** [comment]
Je viens de regarder https://app.beta.francoralite.net/authority/37 : informateur = Charles Aubrière 

Il n'y a qu'un item listé (dont le clic sur l'item ne fait pas consulter l'item en question :-\ ) et j'ai regardé rapidement, cet informateur est étiqueté comme tels au moins deux fois : https://app.beta.francoralite.net/item/22 et https://app.beta.francoralite.net/item/23

**Comment by lluc** [comment]
:information_source:   
## Ajout
Implémenter la même fonctionnalité pour les catégtories de personnes suivantes : 
- enquêteur
- auteur
- compositeur
- éditeur

**Comment by lluc** [comment]
@mnauge :warning:  La notion d'éditeur est rattachée aux enquêtes (collections) et non pas aux items.

**Comment by mnauge** [comment]
Ne fonctionne pour le moment que pour  "Informateurs" j'ai l'impression.
J'ai testé Enqueteur > Harry Oster  sans succès.

**Comment by lluc** [comment]
@mnauge Dans quel(s) item(s) est-il enquêteur ?

**Comment by mnauge** [comment]
dans celui ci par exemple : https://app.beta.francoralite.net/item/48

**Comment by lluc** [comment]
Les test d'intégration du *back* sont corrects.
Cela semble être un problème d'affichage côté *front* : la requête d'API https://app.beta.francoralite.net/api/authority/10/contribs s'effectue correctement. On obtient les Enquêtes : 3, 48 ,49. 
Je regarde de plus près l'affichage de la fiche d'une personne.

**Comment by mnauge** [comment]
ça marche merci.
