### ISSUE TITLE
RECHERCHE AVANCEE > LIEU > Detection de lieux plus large

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#162]

**Comment by Marion-L1** [comment]
**Comment reproduire le problème :**
- Dans le champ de recherche avancée `Lieu`, écrire Noirmoutier

**Effet obtenu :**
- Aucune détection de lieu

**Effet obtenu :**
- Affichage des noms lieux comprenant ce terme (il y en a)

**Comment by lluc** [comment]
@Marion-L1 @mnauge Testé avec la Biroire ici : https://app.francoralite.net/search_advanced/  
Cala semble fonctionner. :thinking:

**Comment by Marion-L1** [comment]
La demande était en fait que l'on puisse rechercher un ensemble de lieux liés à un terme inclu dans sa designation : par exemple que en recherchant le terme "Noirmoutier", l'on puisse faire ressortir toutes les enquêtes réalisées dans un village de l'île de Noirmoutier.
Je clos le ticket car il date un peu et la demande n'est pas claire, mais dis moi si c'est possible à faire non...et dans ce cas on en reparlera peut-être !
