### ISSUE TITLE
Création ITEM > Description > Compositeur(s) > autocomplétion de l'ensemble des personnes entrées

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#163]
**Comment reproduire le problème :**
- Enquête : `Répertoire joué au violon et témoignage de M. Charles Aubrière et Mme Aubrière - La Biroire, 1969`
- Créer un item
- Onglet `Description`
- Champ `Compositeur(s)` : taper "a"

**Effet obtenu :**
- Apparition en autocomplétion de l'ensemble des personnes entrée sur la plateforme contenant la lettre a

**Effet souhaité :**
- Apparition en autocomplétion de l'ensemble des COMPOSITEURS dont le nom comporte la lettre a

-> Absence de ce problème pour le champ AUTEUR

**Comment by mnauge** [comment]
ok
