### ISSUE TITLE
[personne] ajout : amélioration formulaire

### ISSUE THREAD

**Issue by Laurence-Girault** [Francoralite/francoralite#21]
Quand on ajoute une personne :
- mettre un placeholder sur le champ de la date de naissance pour indiquer le format attendu, car utiliser le calendrier pour une personne de plus de 30 ans est fastidieux et par il peut être remplit de la forme jj/mm/aaaa ce qui fonctionne mal.
- le lieu de naissance doit exister dans les lieux pour pouvoir être saisis, pas très intuitif.

**Comment by lluc** [comment]
Le lieu de naissance fait référence à la table des Lieux. Celle-ci doit être saisie avant la création d'une personne ou tout autre entité.  
Reste à voir si coupler la création d'un lieu à la création d'un autre entité ne risque pas d'entraîner des problème d'intégrité référentielle.   
Effectivement, ce serait plus intuitif. :-)
