### ISSUE TITLE
[BUG] Modification impossible

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#238]
**Décrire le problème**
Lorsque je modifie une fiche au niveau Mission et Enquête, je ne peux ni enregistrer ni annuler la modification. La page de modification revient en boucle. 

**Comment reproduire le problème :**
- Onglet Archives, cliquer sur Missions
- UPOI_ATP_0000 puis "Modifier"
- Modifier le titre "Extraits de ATP Mission Noirmoutier 1956"
- Valider

**Effet obtenu :**
- La page de modification de la mission s'affiche de nouveau et les modifications sont effacées

**Effet souhaité :**
- Appartition de la page modifiée

**Comment by mnauge** [comment]
@lluc  sur le site beta, je n'ai plus de bouton pour modifier le niveau enquete....

**Comment by lluc** [comment]
@mnauge effectivement. C'est bizarre, la version locale de développement l'affiche correctement et les tests sont passés ...

**Comment by lluc** [comment]
@mnauge j'ai remarqué que, pour une raison indéterminée, la permission *collection:update* était absente du profil *contributors*.  
J'ai rétabli cette permission, mais elle ne semble pas avoir pris effet. :-(

**Comment by lluc** [comment]
@mnauge Je pense que j'ai trouvé : https://github.com/Francoralite/francoralite/blob/8796f53758dd63f8c855e77b8d2e092099daefa3/francoralite/apps/francoralite_front/views/collection_edit.py#L23

Ce n'est pas bonne permission qui est utilisée (*certainement une conséquence d'un copier/coller ...*)

**Comment by mnauge** [comment]
j'ai réussi à réaliser des modifications sur la beta. 
Nb, j'ai du me délogguer, puis me reloguer. car sinon, je n'avais pas les boutons "editer"...
