### ISSUE TITLE
[BUG] Lieu : création impossible

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#244]
**Décrire le problème**
Il n'est pas possible de créer un nouveau lieu même si toutes les informations obligatoires sont remplies

**Comment reproduire le problème :**
- Aller sur l'onglet "Lieu" puis "ajouter"
- Dans la recherche, taper "Port-Joinville"
- Entrer "Port-Joinville" dans le champ Nom
- Valider

**Effet obtenu :**
- Erreur 500 est affiché sur une page blanche

**Effet souhaité :**
- Redirection sur la fiche du lieu nouvellement créé

**Comment by lluc** [comment]
@Marion-L1 j'ai besoin de 2 petites pécisions :  
- C'est sur quel serveur ? (beta ou prod)
- Avec quel profil de connexion ?

**Comment by Marion-L1** [comment]
C'était sous l'adresse https://app.francoralite.net/
Sous le profil "contributeur"

**Comment by lluc** [comment]
OK.  
Donc c'est sur le site de prod.  
Actuellement, les droits d'un "contributeur" ne permettent pas de créer/modifier un lieu.  
C'est à modifier dans Keycloak. Je regarde cette modification dans les meilleurs délais.

**Comment by mnauge** [comment]
@lluc merci. Je viens de discuter avec @Marion-L1. Nous avons 5 archivistes qui vont documenter nos fonds à partir de la semaine prochaine. Ils vont travailler par tableur. Mais ils vont tout de même créer les lieux manuellement sur la plateforme. Je vais créer des comptes individuels. Donc je confirme qu'il faut qu'ils puissent créer des lieux avec le "droit contributeur" :-)

**Comment by Marion-L1** [comment]
Merci !envoyé : 18 novembre 2021 à 10:14de : lluc ***@***.***>à : Francoralite/francoralite ***@***.***>cc : Marion-L1 ***@***.***>, Mention ***@***.***>objet : Re: [Francoralite/francoralite] [BUG] Lieu : création impossible (Issue #244) OK. Donc c'est sur le site de prod. Actuellement, les droits d'un "contributeur" ne permettent pas de créer/modifier un lieu. C'est à modifier dans Keycloak. Je regarde cette modification dans les meilleurs délais.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mnauge** [comment]
J'ai réussi à créer ce lieu dans la beta.
