### ISSUE TITLE
Ajout de logo partenaire financier

### ISSUE THREAD

**Issue by mnauge** [Francoralite/francoralite#247]
**Objectif**
Est-il possible d'ajouter le logo : https://www.collexpersee.eu/wp-content/uploads/2020/01/logo-collex-signature-dor%C3%A9.png
dans la fenêtre de droite "Partenaires financiers" de la page d'accueil (avant le 08/12/2021) ?
Par avance merci :-)

**Comment by lluc** [comment]
@mnauge Oui, il sera visible lors des prochaine déploiements

**Comment by mnauge** [comment]
C'est parfait! Un grand merci :-D
