### ISSUE TITLE
[BUG] fichiers MP3 à supprimer après les tests unitaires

### ISSUE THREAD

**Issue by fab2713** [Francoralite/francoralite#251]
**Décrire le problème**
Lors que l’on lance des tests unitaires, de nombreux fichiers MP3 sont créés sans être supprimés.
Plus on lance de tests (back ?), plus il y a de fichiers et plus l’instance est longue à démarrer.

**Comment reproduire le problème :**
Lancer les tests unitaires.

**Effet obtenu :**
Les fichiers MP3 sont toujours présents à la fin des tests unitaires.

**Effet souhaité :**
Les fichiers MP3 devraient être supprimés.

**Idée :**
Surcharger la classe `APITestCase` pour les tests qui créent ces fichiers et y ajouter la méthode suivante :
```python
    @classmethod
    def tearDownClass(cls):
        #TODO rm -f /srv/media/items/code*.mp3
        super().tearDownClass()
```

**Comment by fab2713** [comment]
Je suis bien conscient de n’avoir ajouté le `CleanMediaMixin` que dans quelques modules de tests et que d’autres aussi créent des MP3.
Mais normalement, le dernier module de tests qui génère des fichiers est `test_mission` et il a été traité.
Donc il fera le ramasse-miettes pour les autres dans le pire des cas.

**Comment by lluc** [comment]
@fab2713 Bien vu pour le *tearDownClass*.  :+1:
