### ISSUE TITLE
[BUG] Apparition du message Accès interdit de manière aléatoire

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#267]
**Décrire le problème**
Lorsque je tente d'effectuer plusieurs modifications d'affilé, le message Accès interdit apparait à un moment m'empêchant par la suite toute autre modification, alors que je suis connectée.

**Comment reproduire le problème :**
- message qui apparait de manière aléatoire après plusieurs modification ou tentatives de modifications de fiches.

**Comment by mnauge** [comment]
@lluc, il y a peut-être une piste à explorer du côté du acces_token expires_in=300 (ça fait 5 minutes). J'ai l'impression que c'est depuis que vous utilisez plus dans le middleware les droits d'accès gérés par keycloak que les soucis de boutons pour éditer et des accès interdits existent.

**Comment by mnauge** [comment]
Il doit être possible de modifier le access_token expire_in via l'admin keycloak Access Token Lifespan : actuellement à 5 minutes, j'augmente  dans la beta. Il faudra un mecanisme côté front pour indiquer au user que son token a expiré, qu'il doit se reconnecter.

**Comment by mnauge** [comment]
Il y a un problème de synchronisation entre l'information en haut à droite qui indique que nous sommes identifiés alors qu'en réalité nous ne le sommes plus. Par exemple, je m'identifie sur Francoralité, je fais des créations, tout fonctionne. Puis j'éteins mon ordinateur. Je le rallume le lendemain, je vais sur Francoralité qui me dit que je suis connecté, donc je tente des manipulations d'édition, mais il n'y a plus les boutons. Normal, car en réalité mon access token a expiré alors que le front (en haut à droite ne l'indique pas/ ne me demande pas de m'identifier.

**Comment by lluc** [comment]
Je pense qu'il faut que je regarde de près les mécanismes avec @achaussier
