### ISSUE TITLE
[BUG] SON : items dont le son n'est pas écoutable

### ISSUE THREAD

**Issue by Marion-L1** [Francoralite/francoralite#275]
**Décrire le problème**
Il n'est pas possible d'écouter le son des items suivants :
UPOI_GDC_0000_0001_019
UPOI_GDC_0000_0002_003
UPOI_GDC_0000_0002_005

**Comment reproduire le problème :**
- Appuyer sur le bouton play sur le lecteur de son des items ci-dessus

**Effet obtenu :**
- il ne se passe rien

**Effet souhaité :**
- le son e l'item démarre

**Comment by mnauge** [comment]
@Marion-L1 de ce que je constate, c'est que les fichiers audio sont au format .WMA , nous aurions du les convertir en .MP3 avant envoi. Depuis que nous avons delete la dependance à timeside, le transcodage vers MP3 doit être fait avant envoi. Ce n'est plus le server qui le fait.

**Comment by lluc** [comment]
Je confirme : suite à la suppression des dépendances à Timeside il avait été décidé de n'envoyer que des MP3 vers le serveur.

**Comment by mnauge** [comment]
Il faut donc supprimer ces items. Puis les recréer avec un fichier audio au bon format. (via envoi automatisé ;-) ) 
Le transcodage WMA vers MP3 peut se faire massivement assez facilement. Par exemple, depuis le sharedocs Huma-Num, en allant coper/coller les WMA dans le dossier hnTools_watchFolder/Audio/ffmped/toMP3/IN

**Comment by Marion-L1** [comment]
Ok pour la procédure, mais juste pour vous préciser que ce n'est pas moi qui ai créé ces items.

**Comment by mnauge** [comment]
Moi non plus ;-)... Je pense que c'est du très vieux, et que c'est un reste d'une bascule/migration de données où ce cas de figure n'avait pas été pris en compte. Actuellement, je pense que c'est même impossible de réussir à recréer un item dans cet état.

**Comment by Marion-L1** [comment]
Non je pense que c'est Marlène qui l'a fait récemment, ça correspond à des données qu'elle m'a demandées et dont elle a surement besoin pour ses présentations.
J'ai mis les fichiers en .mp3 sur le Sharedoc dans le dossier "Fonds plateforme"
