### ISSUE TITLE
[BUG] [front] Suppression (Code 204) non traitée

### ISSUE THREAD

**Issue by lluc** [Francoralite/francoralite#279]
Suppression (Code 204) non traitée

**Comment reproduire le problème :**

- En administrateur, créer une fiche de type danse, puis la supprimer, via l'interface graphique (*front*)

**Effet obtenu :**

- La fiche est correctement supprimée, mais la page Web affiche "erreur indéterminée"
- Dans la console, il y a le message suivant :
```
File "/srv/app/francoralite/apps/francoralite_front/tools.py", line 74, in check_status_code
raise Exception(HTTP_ERRORS[status_code])
KeyError: 204
```

**Effet souhaité :**

- Afficher un message qui indique que la suppression a été correctement effectuée
- afficher un lien vers la liste des entités concernées

**Comment by mnauge** [comment]
il y a le même soucis pour toutes les suppressions d'énumération. Et il me semble que c'est aussi le cas pour les items.
