### ISSUE TITLE
[BUG] recherche avancée doublon de critère

### ISSUE THREAD

**Issue by mnauge** [Francoralite/francoralite#285]
**Décrire le problème**
les valeurs de filtre se multiplie

**Comment reproduire le problème :**
sur la beta, dans aire culturel, choisir Poitou – Saintonge, clic sur effectuer une recherche.

**Effet obtenu :**
le critère Poitou – Saintonge apparaît 6 fois.

**Effet souhaité :**

le critère n'apparaît qu'une fois

**Comment by fab2713** [comment]
exemple : https://app.beta.francoralite.net/search_advanced/?cultural_area=Poitou+%E2%80%93+Saintonge

**Comment by mnauge** [comment]
@fab2713 (ce n'est pas vraiment le lieu pour ça), mais je n'ai pas ton mail et je crois que Luc est en repos... J'ai noté qu'il manque des "filtres" de recherche (Luc m'avait prévenu). Dans les prioritaires, j'ai en tête la **civilité** et les **cotes**. Qu'en penses-tu ?

**Comment by fab2713** [comment]
Effectivement, ce n’est pas le bon endroit, mais je te réponds rapidement quand même :
Nous avons bien avancé les civilités avec Luc avant ses congés, j’ai prévu de les terminer (probablement demain après-midi) avant son retour, mais pas plus car je n’ai pas beaucoup de disponibilité cette semaine.
Éventuellement, ce bug ci en plus, si c’est suffisamment rapide. ;-)
Pour les cotes, nous verrons probablement la semaine prochaine.
