### ISSUE TITLE
[BUG] Recherche avancée Thématique(s) du témoignage

### ISSUE THREAD

**Issue by mnauge** [Francoralite/francoralite#286]
**Décrire le problème**
la zone de saisie de la thématique ne permet de choisir que certaines valeurs (les 10 première dans l'ordre alphabétique), même si on commence à taper autre chose qu'un A.

**Comment reproduire le problème :**
Dans recherche avancée> genre> Thématique(s) du témoignage> saisir **Fête**

**Effet obtenu :**

- n'est pas proposé de choisir la valeur d'énumération  **Fêtes et coutumes calendaires**

**Effet souhaité :**

- pouvoir choisir cette valeur

**Comment by fab2713** [comment]
Les 9 champs suivants étaient concernés :
- Quoi ? / Type de média
- Quoi ? / Contexte d'enregistrement
- Quoi ? / Danse
- Genres / Thématique(s) du témoignage
- Genres / Genre(s) de la chanson
- Genres / Genre(s) de l’autre expression vocale
- Genres / Genre(s) de l’expression instrumentale
- Genres / Genre(s) du conte
- Textes / Coupe(s)
