### ISSUE TITLE
[recherche avancée] Trier les résultats

### ISSUE THREAD

**Issue by lluc** [Francoralite/francoralite#292]
Pouvoir trier l'affichage des résultats sur les colonnes ; 
- cote
- titre

**Comment by mnauge** [comment]
A l'usage, nous remarquons que nous aimerions que l'information Informateur affiché dans le résultat de recherche item, soit dans l'ordre **Nom puis Prénom**.  Ce n'est probablement pas le meilleur endroit pour dire ça, mais c'est un peu en lien car l'idéal aurait été de pouvoir trier également par ordre alphabétique de nom d'informateur (où est choisi pour ce tri l'informateur le plus décisif dans le tri demandé quand il y a plusieurs informateurs). Mais j'ai bien noté que nous abandonnons pour le moment cette idée.
