### ISSUE TITLE
[page d'accueil] bloc de mise en valeur de certains items/docs/events

### ISSUE THREAD

**Issue by mnauge** [Francoralite/francoralite#300]
**Mode**
- [x] Consultation
- [x] Saisie

**Type**
- fonctionnel
- création de pavé/bloc

**Descriptif**
- Sur la page d'accueil, ajouter un bloc **Focus** permettant de mettre en valeur certains items/docs/évenements. 
Cf. MAPA annexe, id : 2 .

- Donner aux administrateurs la possibilité d’éditer ce contenu en markdown, permettant ainsi d’accéder aux différents contenus de communication récemment produits autours des fonds Francoralité.

Exemple : une conférence utilisant les contenus disponibles sur la plateforme vient d’avoir lieu, il doit pouvoir être possible d’ajouter dans le bloc **Focus** un texte et une image permettant d’aller consulter la vidéo de cet événement. 

Remarque/Pour info : nous envisageons la création d'un site wordpress Université de Poitiers dédié à la création d'article permettant de mettre en valeurs certains événements/items. L'idée est de faire de la plateforme Francoralité la bibliothèque sonore exhaustive, tandis que le wordpress vient en complément pour faciliter la création d'objet/article de médiation/communication de certains items saillants.

**Comment by lluc** [comment]
@mnauge Cette fonctionnalité ne risque pas de faire "double emploi" avec le site Wordpress existant ? :thinking:

**Comment by lluc** [comment]
@mnauge Oui, car cela impliquerait de développer une partie des fonctionnalités que vous avez déjà sur le site Wordpress.

**Comment by mnauge** [comment]
@lluc je pense qu'avec simplement une zone éditable markdown on peut s'en sortir sur notre bibliothèque sonore. On peut partir du principe que les images à afficher dans notre markdown sont des images distantes déjà rendu public depuis le wordpress.
