### ISSUE TITLE
[BUG] recherche avancée recherche par cote

### ISSUE THREAD

**Issue by mnauge** [Francoralite/francoralite#314]
**Décrire le problème**
lors de la saisie d'une **cote mission** dans le champ de recherche Cote, il ne sort pas les bon(nes) enquetes/items

**Comment reproduire le problème :**

- saisir la cote de mission UPOI_ATP_0002

**Effet obtenu :**
il sort des enquêtes qui n'ont pas du tout cette cote

**Effet souhaité :**

avoir les enquetes et items fils de la mission dont la cote est précisée.

Le cas d'usage réel ciblé est de choisir dans cote (avec des OU) 3 cotes de missions et genre : chanson.

Il faut que le champ de recherche cote soit intelligent, qu'il puisse gérer à la fois des cotes fonds, des cotes missions, des cotes enquetes, des cotes items. c'est réalisable en intégrant une détection du nombre de underscore pour savoir si ça doit chercher au niveau mission ou au niveau enquete etc...

**Comment by lluc** [comment]
@michael Cela semble être un problème de saisie : si on écrit le code d'une mission sans la choisir dans la liste déroulante, cela  ne filtre pas (et on a tout les enregistrements)

Sinon, cela fonctionne et on obtient l'URL suivante :
`https://app.beta.francoralite.net/search_advanced/?code_internal=UPOI_ATP_0002&code_internal_operator=or&code_external_operator=or&title=&description=&informer_civility_operator=or&informer_operator=or&collector_civility_operator=or&collector_operator=or&date_start=&date_end=&location_operator=or&cultural_area_operator=or&media_type_operator=or&language_operator=or&recording_context_operator=or&usefulness_operator=or&dance_operator=or&thematic_operator=or&domain_song_operator=or&timbre_operator=or&timbre_ref_operator=or&coupe_operator=or&domain_vocal_operator=or&coirault_operator=or&domain_music_operator=or&instrument_operator=or&domain_tale_operator=or&text=&incipit=&refrain=&jingle=`

**Comment by mnauge** [comment]
ok, je viens de tester ton url, ça marche ! Petit problème, je viens d'essayer de faire une nouvelle recherche sur UPOI_ATP_0001 et l'assistant à la saisie ne me propose pas ma valeur, donc j'ai le même soucis.

**Comment by lluc** [comment]
:thinking: A priori, ça fonctionne aussi  ...  
`
https://app.beta.francoralite.net/search_advanced/?code_internal=UPOI_ATP_0001&code_internal_operator=or&code_external_operator=or&title=&description=&informer_civility_operator=or&informer_operator=or&collector_civility_operator=or&collector_operator=or&date_start=&date_end=&location_operator=or&cultural_area_operator=or&media_type_operator=or&language_operator=or&recording_context_operator=or&usefulness_operator=or&dance_operator=or&thematic_operator=or&domain_song_operator=or&timbre_operator=or&timbre_ref_operator=or&coupe_operator=or&domain_vocal_operator=or&coirault_operator=or&domain_music_operator=or&instrument_operator=or&domain_tale_operator=or&text=&incipit=&refrain=&jingle=`
