### ISSUE TITLE
[menu horizontal de navigation] Evolution

### ISSUE THREAD

**Issue by mnauge** [Francoralite/francoralite#319]
**Mode**
- [x] Consultation
- [ ] Saisie

**Type**

- place des informations
- esthétique

**Descriptif**
Distribuer différemment les menus/sous menus pour réduire le nombre de menu.
- Renommer "Archives" en "Archives sonores"
- déplacer institution sous archive sonore
- Renommer Enumération en Thésaurus

Liste sous Thésaurus : 
- Personnes → Enquêteurs + Informateurs + Auteurs + Compositeurs + Editeurs
- Lieux
- Aires culturelles
- Langues
- Thématiques
- Musique → Genre d'autre expression vocale + Genre de musique instrumentale + Natures des émissions vocales + Instruments-Voix + Classification Hornbostel-Sachs + Fonction + Organisation musicale + Formation
- Chanson → Genre de chanson + Coupes + Catalogages Coirault + Catalogages Laforte
- Conte → Genre de conte + Catalogages Delarue-Tenèze + Catalogages Aarne-Thompson
- Danses
- Contextes d'enregistrement
- Type de média

**Comment by lluc** [comment]
@mnauge  
> Clic sur Archives sonores amène à la liste des institutions  

:question:  On garde tout de même le menu déroulant en dessous (Fonds,Missions, Enquêtes, Items) ?

**Comment by mnauge** [comment]
@lluc, c'est @Marion-L1 qui va remettre très prochainement au propre l'attendue en rééditant l'issue.

**Comment by Marion-L1** [comment]
@lluc : Oui on garde le menu déroulant dessous Archives sonores

**Comment by Marion-L1** [comment]
@lluc @mnauge : j'ai mis à jour l'ordre d'appartition des éléments sous Thésaurus dans la description de l'issue

**Comment by mnauge** [comment]
@lluc 

Liste sous Thesaurus :
- « Lieux » n’apparait pas, il est toujours à coté du Thesaurus et non en-dessous. 
- « Langues » est bien sous le Thesaurus, mais n’est pas à la bonne place, tout comme « Thématique » et « Chanson » et « Danse » sont toujours dans « Genre ». Problème aussi avec « Type de média ». « Contextes d’enregistrement n’est pas non plus à la bonne place.

**Comment by Marion-L1** [comment]
> @Marion-L1 peux-tu vérifier si le menu te convient stp ?

Dans Thésaurus → Musique : les informations ne sont pas dans l'ordre indiqué

Si on est sur la page d'accueil et que l'on veut consulter les différentes informations de Thésaurus → Musique, une partie est coupée par le géonavigateur.
