### ISSUE TITLE
[widget dataviz pour tableau] Quantité d'items par domain

### ISSUE THREAD

**Issue by mnauge** [Francoralite/francoralite#320]
**Mode**
- [x] Consultation
- [ ] Saisie

**Type**

- fonctionnel
- esthétique

**Descriptif**
Créer un widget intégrable dans les tableaux qui liste les Fonds/Missions/Enquêtes capables de rendre visible la quantité d'items fils par domain. S'inspirer de ce qui est proposé sous git : barre horizontale colorée par type de code.
Partons sur une version compact avec information/légende : nom du domain : pourcentage/valeur absolue dans info bulle. 

Pour les couleurs, s'inspirer de ce qui proposé dans plotly.colors.qualitative : https://plotly.com/python/discrete-color/

La palette ploty me semble bien : 
-  Témoignage : bleu #636EF4
- Chanson : rouge ....
- Autre expression vocale : vert
- Expression instrumentale : violet
- Conte ou récit légendaire : orange

**Comment by mnauge** [comment]
Parfait !

**Comment by mnauge** [comment]
Bien qu'une explication apparaisse si on laisse sa souris, les différents utilisateurs me disent qu'il manque une légende toujours visible.

**Comment by lluc** [comment]
@mnauge OK, mais dans ce cas là, où doit-on positionner la légende ?

**Comment by mnauge** [comment]
en haut à droite au dessus du tableau a proximité de domain ?!

**Comment by fab2713** [comment]
Finalement, j’ai mis la légende sous le tableau à droite pour afficher plus de lignes sans défiler que si c’était au dessus.
Mais si besoin, il est possible de la mettre au dessus en plus, ou à la place de dessous.

**Comment by mnauge** [comment]
@fab2713 bonne initiative. C'est très bien en bas. Merci
