### ISSUE TITLE
[BUG] tests unitaires en échec pour les fonds

### ISSUE THREAD

**Issue by fab2713** [Francoralite/francoralite#335]
**Décrire le problème**
Les tests `test_fonds_details` et `test_fonds_add` ne passent plus.

**Comment reproduire le problème :**

- lancer les tests `test_fonds_details` et `test_fonds_add` ou consulter [cette page](https://github.com/Francoralite/francoralite/actions/runs/3152615851/jobs/5128060169) pour plus de détails.

**Effet obtenu :**

- les tests échouent

**Effet souhaité :**

- les tests réussissent

**Comment by lluc** [comment]
@fab2713 Je ne suis pas certain que la version de *firefox-esr* soit, au final, celle que l'on veut.  
Lors de l'installation des dépendances pour l'exécution des tests (en local), il est écrit le message suivant :  
```
The following packages will be DOWNGRADED:
  firefox-esr
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 48 not upgraded.

```

Sur le CI/CD (Github actions), il y a un soucis avec *firefox-esr*, ici :  
https://github.com/Francoralite/francoralite/actions/runs/3152615851/jobs/5128060169#step:10:1910

**Comment by fab2713** [comment]
@lluc C’était un problème de version lié à ton installation existante. La suppression des volumes a permis de corriger cela en repartant d’une configuration vierge.
