### ISSUE TITLE
[Acceuil] Changement de texte et logo

### ISSUE THREAD

**Issue by mnauge** [Francoralite/francoralite#340]
**Mode**
- [x] Consultation
- [ ] Saisie

**Type**
- changer du texte

**Descriptif**
1. Mettre ce texte :  

# Francoralité : Bibliothèque Sonore et multi-média

## Présentation
Cette Bibliothèque Sonore regroupe les fonds de littérature orale collectés dès les décennies 30-40 du XXe siècle dans la ruralité du Centre-Ouest français, du Canada francophone et de la Louisiane. Elle formalise un socle culturel cohérent qui s’étale sur ces différents territoires sur plus de quatre siècles d’histoire.

## Organisation de la Bibliothèque Sonore
Le catalogue est organisé en 5 niveaux : [Institutions](https://app.beta.francoralite.net/institution) (emplacement propre à chacun des partenaires scientifiques), [Fonds](https://app.beta.francoralite.net/fond), [Missions](https://app.beta.francoralite.net/mission), [Enquêtes](https://app.beta.francoralite.net/collection), et [Items](https://app.beta.francoralite.net/item). Le niveau principal de description est l’Enquête.

Chaque enquête regroupe l’ensemble des fichiers audio (Items) collectés auprès d’une même [personne](https://app.beta.francoralite.net/authority) (ou groupe de personnes), le même jour en un même lieu. Les enquêtes répondant d’un ensemble cohérent ou collectées sur une même année sont regroupées en Missions qui, réunies autour d’un collecteur, constituent le niveau Fonds.

Le nombre d’enregistrements mis en ligne sur la plateforme est en constante augmentation. Les fiches descriptives sont renseignées de manière collaborative par les différents partenaires de la plateforme.

2. Mettre le nouveau logo en haut à coté du logo de l'Université de Poitiers
![Logo Mix - Couleur](https://user-images.githubusercontent.com/30431973/195376466-f860ef9f-2940-41e2-aecb-648807f6858b.png)

3. Mettre la nouvelle icone d'onglet de page
![Icone V2 - Couleurs](https://user-images.githubusercontent.com/30431973/195376877-0092a941-6257-45fc-91f1-757fdaed5cca.png)

**Comment by mnauge** [comment]
@lluc désolé pour cette demande bonus. On arrive au moment où c'est important de soigner les détails de la page d'accueil :-)
J'imagine et j'espère que ce n'est pas trop compliqué de faire ces modif. ;-)

**Comment by fab2713** [comment]
@mnauge Serait-il possible d’avoir les 2 images en format vectoriel (par exemple en SVG) stp ?

**Comment by mnauge** [comment]
@fab2713 les voici : 
![Logo Mix  - Couleurs](https://user-images.githubusercontent.com/30431973/195792950-15488240-4f9d-489f-ac1f-69f2f1afb810.svg)

![Icone V2 - Couleurs](https://user-images.githubusercontent.com/30431973/195793009-8f0502df-b352-46d9-baaa-4afcb8f939db.png)

**Comment by fab2713** [comment]
@mnauge merci pour la première qui semble OK, la seconde semble toujours en PNG par contre ;)

**Comment by mnauge** [comment]
@fab2713 
![Icone V2 - Couleurs](https://user-images.githubusercontent.com/30431973/195908464-c025fbf3-65e6-462a-841f-a8df119655d5.svg)

**Comment by fab2713** [comment]
parfait, merci beaucoup
