### ISSUE TITLE
[BUG] Get skos_concept problème de droits

### ISSUE THREAD

**Issue by mnauge** [Francoralite/francoralite#371]
**Décrire le problème**
alors qu'il est possible de faire un Get skos_concept  sans être identifié (mauvais AUTH_BEARER ), 
la même requête avec un AUTH_BEARER valide provoque une erreur 403.

**Effet souhaité :**

Que ce type de requête fonctionne aussi lorsque l'on ai correctement identifié.

**Comment by mnauge** [comment]
Je ne sais pas si c'est lié, mais je n'arrive pas à ajouter de référence coirault à mes items, ni manuellement, ni via l'api POST ​/api​/item​/{item_pk}​/coirault.

**Comment by mnauge** [comment]
@lluc Ces nouveaux tests passent ?

**Comment by lluc** [comment]
@mnauge Vraisemblablement un problème de paramétrage de droits dans Keycloak ( concernant l'accès à la ressource skos_concept )
