### ISSUE TITLE
[BUG] Le thesaurus Aire Culturel n'est pas éditable par UIX

### ISSUE THREAD

**Issue by mnauge** [Francoralite/francoralite#372]
**Décrire le problème**
Le thesaurus Aire Culturel n'est pas éditable par UIX

**Comment reproduire le problème :**

- Clquer sur les menus : Thesaurus>Aire Culturel

**Effet obtenu :**

- dirige vers la page https://app.francoralite.net/api/cultural_area/

**Effet souhaité :**

- diriger vers une interface permettant l'édition des aires culturels à la manière du thésaurus Language

**Comment by bpradines** [comment]
L'édition est maintenant possible (en tant qu'administrateur ! car il ne faut pas supprimer ce qui est déjà relié à des données)
