### ISSUE TITLE
[BUG] erreur 404 pour item/coupe : manque de cohérence

### ISSUE THREAD

**Issue by mnauge** [Francoralite/francoralite#374]
**Décrire le problème**
contrairement à toutes les autres enumerations, la coupe est intégré directement dans l'item sans table intermédiaire. Il faudrait la faire sortir pour être cohérent avec les autres énumérations. Prendre exemple sur l'enum language

**Comment reproduire le problème :**

- faire une requete GET sur https://app.francoralite.net/api/item/641/coupe

**Effet obtenu :**

- 404

**Effet souhaité :**

- comme https://app.francoralite.net/api/item/641/language

**Comment by lluc** [comment]
@mnauge  Si, comme prévu, il n'y a bien qu'une (et une seule) coupe par item, c'est normal ( pas de relation *plusieurs-à-plusieurs* )
L'item stocke l'identifiant de la coupe. 
Les notes de la coupe, par contre, se trouve dans la table Coupe :  https://app.francoralite.net/coupe

**Comment by mnauge** [comment]
ok, c'est normal, je ne vais pas utiliser ma fonction generic sync_Enum, mais plutôt utiliser un "patch".
