### ISSUE TITLE
[BUG] Recherche avancée ne fonctionne pas

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#380]
**Décrire le problème**

- Parfois la recherche avancée met un temps fou à répondre, la liste des résultats est très longue et n'a rien à voir avec la demande, le temps de chargement de la page de résultats dépasse 5 minutes 

ou bien

- Message "502 Bad getway" de nginx, et l'URL affichée dans la barre d'adresse est :

https://app.francoralite.net/search_advanced/?code_internal_operator=or&code_external_operator=or&title=&description=&informer_civility_operator=or&informer_operator=or&collector_civility_operator=or&collector_operator=or&date_start=&date_end=&location_operator=or&cultural_area_operator=or&media_type_operator=or&language_operator=or&recording_context_operator=or&usefulness_operator=or&dance_operator=or&thematic_operator=or&domain_song_operator=or&timbre_operator=or&timbre_ref_operator=or&coupe_operator=or&domain_vocal_operator=or&coirault_operator=or&domain_music_operator=or&instrument_operator=or&domain_tale_operator=or&text=&incipit=&refrain=&jingle=

**Comment reproduire le problème :**

- Cliquer sur l'onglet "Recherche avancée", déplier le champ "Où ?", dans "Lieu" taper Cherves, puis cliquer sur le bouton pour lancer la recherche.

**Effet obtenu :**

- la recherche avancée met un temps fou à répondre, la liste des résultats est très longue et n'a rien à voir avec la demande, le temps de chargement de la page de résultats dépasse 5 minutes 

Pour le message 502 Bad Getway ça se produit aléatoirement, quand le serveur n'a pas le temps de renvoyer les premiers résultats incohérents.

**Comment by bpradines** [comment]
Bonjour Luc,

Ton diagnostic semble le bon.

Je propose, pour donner confiance aux utilisateurs et comprendre ce qui se passe :

- afficher un message d'erreur ET ne pas lancer la requête, quand tu détectes qu'aucun champ de recherche n'est rempli (ex. de message : "Rien à rechercher. Merci de remplir au moins un critère de recherche."). Comme ça l'utilisateur verra que son critère de recherche n'est pas reconnu.
- avant les résultats de recherche, mets un petit encadré "Votre recherche :" avec une ligne par critère reconnu (ex.: "Lieu : Cherves") pour savoir ce que tu affiches vraiment. En dernière ligne, tu mets le nombre de résultats trouvés (XXX Résultats). Ca aidera à comprendre ce qui se passe.
- mets en place la pagination des résultats avec une ligne de contrôles au-dessus ET en-dessous des résultats : Page X / XXX, liste déroulante du choix du nb. de résultats par page (10, 50 ou 100 - 10 par défaut) et les contrôles de navigation de pages (première / précédente / suivante / dernière).
- dans les champs de saisie où l'on doit choisir une valeur prédéfinie plutôt qu'une saisie libre, dès le premier caractère tapé, déroule la liste des choix possibles automatiquement, et si aucun choix n'est fait (ESC, clic à côté, ...), efface le champ de saisie !!!

Si tu fais du CI/CD, vas-y.

**Comment by lluc** [comment]
OK, je vois avec @fab2713 d'ici à la semaine prochaine.
