### ISSUE TITLE
[sys] Numéro de build/version

### ISSUE THREAD

**Issue by lluc** [Francoralite/francoralite#388]
**Mode**
Consultation

**Type**

- fonctionnel

**Problème**
Pouvoir connaître le numéro de build ou bien la version  en cours d'utilisation

**Descriptif**
Il est toujours instructif, sur un serveur donné ( pré-production, production, ... ) de connaître la version qui a été déployée.

**Comment by bpradines** [comment]
@lluc , sur la version beta, en bas d'écran, l'encadré "Contact" ne s'affiche pas en-dessous de "Partenaires", c'est normal ?

**Comment by lluc** [comment]
@bpradines je pense que c'est un oubli. Je vais voir avec @fab2713, au cas où il y aurait eu une interaction avec les changement au sein des bibliothèques d'affichage.

**Comment by bpradines** [comment]
@lluc Numérotation des versions : 

Peux-tu faire un tag sur ton dernier commit avec le N° de version en partant de 1.0.0 beta ? 
A chaque nouvelle beta tu incrémentes le dernier chiffre, et à chaque plus gros changement tu incrémentes l'avant-dernier.

Ca permettrait d'avoir la date de chaque version (y compris les betas) dans la liste des tags. 
Et pour les non-beta (déployées sur la prod), faire aussi une Release ...

Si tu peux mettre en note la liste des changements (titres des issues qui sont dans deployed) pour qu'on s'y retrouve, comme ça on aura un historique facilement lisible des changements de chaque version.

En bas de l'écran, avant le N° de commit, peux-tu afficher le tag et la date : V. 1.0.0 beta du 27/11/2023 - <tes références : N° commit ...>

Merci par avance

**Comment by lluc** [comment]
@bpradines il n'y aura pas de mention "beta", car on déploie en prod une version qui a été validée en beta.

**Comment by bpradines** [comment]
> @bpradines il n'y aura pas de mention "beta", car on déploie en prod une version qui a été validée en beta.

OK je comprends. Ca simplifie aussi...

**Comment by lluc** [comment]
@bpradines Pour une raison indéterminée, il semble que l'enregistrement suivant ait été supprimé de la table **block** :


```json
{
    "id": 5,
    "type": null,
    "title": "Contact",
    "content": "*Nous vous invitons, utilisateurs, chercheurs et familles des témoins à nous contacter si vous voyez des erreurs, incohérences, si vous reconnaissez un·e proche et/ou que vous êtes en désaccord avec la diffusion du témoignage/document vous ou le·la concernant.* \r\n**francoralite-contact@groupes.renater.fr**",
    "order": 5,
    "show": true
  }
```

Ce qui explique l'absence d'affichage du bloc *contact*.

**Comment by bpradines** [comment]
> @bpradines Pour une raison indéterminée, il semble que l'enregistrement suivant ait été supprimé de la table **block** :
> 
> ```json
> {
>     "id": 5,
>     "type": null,
>     "title": "Contact",
>     "content": "*Nous vous invitons, utilisateurs, chercheurs et familles des témoins à nous contacter si vous voyez des erreurs, incohérences, si vous reconnaissez un·e proche et/ou que vous êtes en désaccord avec la diffusion du témoignage/document vous ou le·la concernant.* \r\n**francoralite-contact@groupes.renater.fr**",
>     "order": 5,
>     "show": true
>   }
> ```
> 
> Ce qui explique l'absence d'affichage du bloc _contact_.

Il faudrait peut-être reprendre les données de la prod, dans la mesure du possible (pas tout évidemment) ?

**Comment by lluc** [comment]
> Il faudrait peut-être reprendre les données de la prod, dans la mesure du possible (pas tout évidemment) ?

Non, la re-création de cet enregistrement devrait suffire.

**Comment by mnauge** [comment]
On se sert de la beta pour tester des fonctionnalités avec un jeu de data minimal
on n'a jamais essayé de garder les datas à jour sur la beta. tels quelles sont sur la prod.

**Comment by lluc** [comment]
Message   
> fatal: No names found, cannot describe anything.

En pied de page

**Comment by bpradines** [comment]
> Peut-être un début de réponse ici : https://stackoverflow.com/questions/4916492/git-describe-fails-with-fatal-no-names-found-cannot-describe-anything

Et plus simplement, la commande :
git tag --list
et prendre la dernière ligne du résultat ?

**Comment by lluc** [comment]
@bpradines  Oui, ça devrait pouvoir le faire aussi.

**Comment by bpradines** [comment]
Ce coup-ci ça marche 👍
