### ISSUE TITLE
Recherche rapide et avancée - Intégrer champ 'Laforte'

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#391]
Champs additionnels en base de données - Thésaurus Laforte : 
- Intégrer ce champ 'Laforte' #dans le système de recherche avancée.
- Changer le libellé affiché : Coirault → Titre référencé et cote Coirault ; 
- Changer le libellé affiché : Laforte → Titre référencé et cote Laforte.

**Comment by Marion-L1** [comment]
Modification ok pour la recherche avancée
Modification non réalisée pour l'affichage au niveau Item

**Comment by lluc** [comment]
@bpradines à tester dès que le champ Laforte sera opérationnel en saisie dans un fiche d'un Item
