### ISSUE TITLE
Intégration de Thésaurus (Laforte)

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#392]
Champs additionnels en base de données - Thésaurus Laforte : 
- Importer les valeurs de ce thésaurus depuis le tableur Correspondances Coirault-Laforte.xlsx en pièce jointe
[Correspondances Coirault-Laforte.xlsx](https://github.com/Francoralite/francoralite/files/13447283/Correspondances.Coirault-Laforte.xlsx)

**Comment by bpradines** [comment]
@lluc Je note que tu as repris le fichier Excel de Michael correspondant aux fichier Word de Marlène de correspondances Coirault-Laforte. C'est le seul fichier qui soit OK au niveau des droits selon Michael, donc on remplit le thésaurus Laforte avec ça sur la version beta.

**Comment by lluc** [comment]
> @lluc C'est le seul fichier qui soit OK au niveau des droits selon Michael, donc on remplit le thésaurus Laforte avec ça sur la version beta.
@bpradines C'est effectué. :heavy_check_mark:
