### ISSUE TITLE
Champs additionnels en base de données - champ 'Civilités' - Séparer les termes

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#397]
Champs additionnels en base de données - champ 'Civilités' :
- séparer les termes en termes indépendants

**Comment by lluc** [comment]
@bpradines Pourrais-tu préciser ta demande, avec un exemple ? :thinking:

**Comment by bpradines** [comment]
> @bpradines Pourrais-tu préciser ta demande, avec un exemple ? 🤔

Il faudrait pouvoir saisir plusieurs civilités "disjointes" : M + Mme + ... => Thésaurus de civilités

**Comment by Marion-L1** [comment]
Les termes "Jeunes hommes" et "Jeunes filles" sont toujours groupés, et ne sont pas indépendants, de même que "M. ; Mme" et "Mme ; M." qui pourraient disparaître. 
Je n'ai pas accès directement au thésaurus en question pour faire ces changements...

**Comment by Marion-L1** [comment]
Je n'ai pas d'accès au thésaurus pour faire des modifications afin de disjoindre les civilités et faire plus de tests.

**Comment by bpradines** [comment]
> Je n'ai pas d'accès au thésaurus pour faire des modifications afin de disjoindre les civilités et faire plus de tests.

J'ai l'impression que les civilités sont déjà disjointes. Avant elles n'existaient pas du tout en tant que thésaurus (voir version en prod) ...

**Comment by lluc** [comment]
@Marion-L1 Normalement, il faut avoir les droits administrateur pour pouvoir modifier ce thésaurus.
Donc, voir avec @bpradines .

**Comment by Marion-L1** [comment]
@bpradines Oui, certaines paraissent disjointes en effet, mais Jeune homme et Jeune fille par exemple ne paraissent pas l'être...

**Comment by bpradines** [comment]
Attention @Marion-L1 : dans les tableurs, quand on va saisir des noms de personnes, il faudra commencer par saisir la civilité ! Et s'interdire de mettre M. ou Mme ou ... comme prénom quand il n'y en a pas !!!

**Comment by Marion-L1** [comment]
@bpradines > Attention @Marion-L1 : dans les tableurs, quand on va saisir des noms de personnes, il faudra commencer par saisir la civilité ! Et s'interdire de mettre M. ou Mme ou ... comme prénom quand il n'y en a pas !!!
Il va falloir qu'on en reparle...car ce n'est pas le protocole qui avait été réfléchi et mis en place jusqu'à présent avec Michaël...et que nous appliquons déjà pour l'ensemble de nos fonds et de nos tableurs. Cela va nécessiter beaucoup de changements par rapport à ce qui se fait déjà. J'aimerais comprendre un peu mieux les enjeux. 
J'éspère qu'on aura le temps d'en parler demain.

**Comment by mnauge** [comment]
> @bpradines > Attention @Marion-L1 : dans les tableurs, quand on va saisir des noms de personnes, il faudra commencer par saisir la civilité ! Et s'interdire de mettre M. ou Mme ou ... comme prénom quand il n'y en a pas !!! Il va falloir qu'on en reparle...car ce n'est pas le protocole qui avait été réfléchi et mis en place jusqu'à présent avec Michaël...et que nous appliquons déjà pour l'ensemble de nos fonds et de nos tableurs. Cela va nécessiter beaucoup de changements par rapport à ce qui se fait déjà. J'aimerais comprendre un peu mieux les enjeux. J'éspère qu'on aura le temps d'en parler demain.

Je crois qu'il n'y a aucune modification à faire. Je crois que l'information qu'il te manque Bernard, c'est qu'il y a une contrainte d'intégrité dans la base de donnée actuelle qui impose la présence obligatoire du nom et du prénom. Donc pour pousser des données sans changer cette vieille contrainte en BDD, nous avions convenu de règles avec Marion.  

Pour les personnes il y a tableur spécifique où tous les champs sont bien séparés. Dans le tableur des enquetes/items les documentalistes indiquent les personnes sous un format qui doit simplement permettre de les retrouver dans le tableur Personne.

**Comment by bpradines** [comment]
@mnauge OK je comprends mieux.
@fab2713 je te mets un exemple de tableur Personnes pour que tu vois des exemples de civilités : 
[meta-ATP_Personnes2023-10-02ML.xlsx](https://github.com/Francoralite/francoralite/files/14167223/meta-ATP_Personnes2023-10-02ML.xlsx)

**Comment by fab2713** [comment]
@bpradines Ce n’est pas nécessaire, je m’occupe uniquement de découper les données existantes lorsque c’est nécessaire.
Pour les nouvelles données (donc issues du tableur), je pense que ce sera plutôt du côté du script d’import qui utilise l’API qu’il faudra faire quelques ajustements (car l’API a suivi la nouvelle structure de données pour plus de cohérence).

**Comment by bpradines** [comment]
@fab2713 oui mais tu parlais de séparer sur le point-virgule et dans les civilités il y a des point-virgule, par exemple : "Jeune homme ; Jeune fille" est une civilité (il n'y a rien à séparer).

**Comment by mnauge** [comment]
> @fab2713 oui mais tu parlais de séparer sur le point-virgule et dans les civilités il y a des point-virgule, par exemple : "Jeune homme ; Jeune fille" est une civilité (il n'y a rien à séparer).

Euh...Je pense que ça doit faire deux civilités. Enfin je pense.

**Comment by bpradines** [comment]
@mnauge donc il faut bien modifier le tableur personnes ? (regarde l'exemple de fichier)

**Comment by Marion-L1** [comment]
> @bpradines @fab2713 
D'une manière générale, dans nos données, le point-virgule fait systématiquement office de séparateur.

**Comment by bpradines** [comment]
@Marion-L1 L'éclatement des civilités me semble correct (voir le thésaurus des civilités sur la beta). Qu'en penses-tu ?

**Comment by Marion-L1** [comment]
> @Marion-L1 L'éclatement des civilités me semble correct (voir le thésaurus des civilités sur la beta). Qu'en penses-tu ?

C'est super comme ça ! Merci !

**Comment by Marion-L1** [comment]
Les termes utilisés sont-ils modifiables dans un second temps ou faut-il qu'ils soient parfaits tout de suite ?
Il y a deux Mademoiselle : Mlle et Melle, et d'après les règles d'orthographe il faudrait ne laisser que Mlle.

**Comment by bpradines** [comment]
Il faut demander à @lluc ce qui est possible de faire pour regrouper les entrées liées à Melle avec celles liées à Mlle (dans l'idée de supprimer Melle après).

**Comment by bpradines** [comment]
> Les termes utilisés sont-ils modifiables dans un second temps ou faut-il qu'ils soient parfaits tout de suite ? Il y a deux Mademoiselle : Mlle et Melle, et d'après les règles d'orthographe il faudrait ne laisser que Mlle.

@Marion-L1 Renseignement pris, il faut attendre le paiement de la facture de Luc pour déployer la v1.3 en production. Suite à ce déploiement, le thésaurus des civilités va apparaître sur la version de production, et les civilités deront éclatées à chaque point-virgule (ex.: M. ; Mme -> M. et Mme). Alors seulement on pourra demander au cas par cas le regroupement des civilités (ex.: Melle et Mlle -> Mlle). Car le déploiement de la v1.3 va faire apparaître certainement d'autres civilités à regrouper.

=> Il faut attendre le déploiement en production, et à ce moment-là faire une Issue pour demander les regroupements.
