### ISSUE TITLE
Champs additionnels en base de données - Aire culturelle : déplacer vers lieu/location_gis + liste multi-valuée

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#398]
Champs additionnels en base de données - Aire culturelle : 
- déplacer le champ au niveau de la table lieu/location_gis
- le transformer une liste fermée multivaluée (et non une simple chaine de caractère au niveau enquête comme actuellement).

**Comment by bpradines** [comment]
> Relié à l'issue #372

Oui on veut passer d'un champ texte libre à une vrais table 'aire culturelle', et une association N:N (associer plusieurs aires culturelles à un même item). Le top serait de définir une aire en géoJSON ...

**Comment by lluc** [comment]
@bpradines @fab2713 
OK. Quelques précisions :
-  le source actuel qui fournit  les aires culturelles : https://github.com/Francoralite/francoralite/blob/develop/francoralite/apps/francoralite_api/views/cultural_area.py
- composition de la table à prévoir :
    - ID
    - name (texte)
    - geojson (texte, long)
    
 Dans l'immédiat, il y a la possibilité de créer le GeoJSON d'une aire culturelle avec un outil extrerne, tel que UMap (    http://umap.openstreetmap.fr/fr/ )

**Comment by bpradines** [comment]
Comme dit @Marion-L1 : - Aires culturelles, ainsi que leur géo-localisation (voir d'abord liste actuelle, l'enrichir, et chercher rectangles de géo-localisations) : c'est une très bonne idée, la géo-localisation des aires culturelles ! Je vous joins les deux cartes qui nous servent de repère pour les aires culturelles poitevines. 

![Aires culturelles - www lanouvellerepublique frniortque-reste-t-il-du-poitou](https://github.com/Francoralite/francoralite/assets/79471095/dc22ab62-8c6a-4b74-8101-4bf3bdcc3b4f)
![Aires culturelles Vidal-Lablache_n°9_-_Provinces_en_1789](https://github.com/Francoralite/francoralite/assets/79471095/d83cd486-8633-4d8b-8365-733de2dbdd5f)

Nous avions déjà sollicité nos partenaires afin qu'ils nous envoient des informations sur la géographie de leurs aires culturelles, mais sans réponse. Je peux les relancer mais ça va prendre un peu de temps.
Dans tous les cas ça nous paraîtrait important, si possible, d'individualiser les termes afin que la recherche corresponde à différents types de demandes. Les termes seraient (non exhaustif) :
Poitou, Haut-Poitou, Bas-Poitou, Aunis, Saintonge, Angoumois, Île d'Yeu, Île de Noirmoutier, Île d'Oléron, Île de Ré, Louisiane, Nouveau-Brunswick, Péninsule acadienne, Nouvelle-Ecosse, Baie Sainte-Marie, Cap-Breton, Îles de la Madeleine, Québec, Gaspésie, Saguenay, Terre-Neuve, Péninsule de Port-au-Port.

**Comment by bpradines** [comment]
Il faut : 
- au niveau du script de fab, sur les données de production, il faudrait : 
-> séparer "Poitou; bas Poitou" en "Poitou" et "Bas Poitou" dans les affectations existantes
-> à la fin, supprimer "Poitou; bas poitou" de la liste des aires culturelles
-> pareil pour les entrées ou il y a un point-virgule
- Ensuite manuellement je créerai la liste de Marion ci-dessus
- Enfin on pourra créer les cartes dans la base de prod plus tard

@Marion-L1 dans les tableurs il faudra séparer les entrées "poitou; bas poitou" en deux valeurs "poitou" et "bas poitou" et faire comme pour les autres champs multi-valués : par exemple quand il y a plusieurs personnes.

**Comment by fab2713** [comment]
@bpradines ok, je vais procéder à la séparation des termes sur le point virgule (idem pour les civilités)

**Comment by Marion-L1** [comment]
@bpradines Ok ! Si je comprends bien la demande, je pense que c'est déjà ce qui se fait.
