### ISSUE TITLE
Champs additionnels en base de données - ajout 'Précision danse'

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#399]
Champs additionnels en base de données - ajout 'Précision danse' :
- ajout champ texte libre

**Comment by lluc** [comment]
Ajouter un champ "Précision" pour le domaine "Danse"

**Comment by lluc** [comment]
@bpradines Ce champ précision concerne la saisie d'un item ou bien la saisie d'un thésaurus Danse ?

**Comment by bpradines** [comment]
> @bpradines Ce champ précision concerne la saisie d'un item ou bien la saisie d'un thésaurus Danse ?

Champ texte libre, pas de thésaurus en plus, seule @Marion-L1 peut dire

**Comment by Marion-L1** [comment]
Je confirme : les "précisions" sont des espaces de texte libre
> > @bpradines Ce champ précision concerne la saisie d'un item ou bien la saisie d'un thésaurus Danse ?
> 
> Champ texte libre, pas de thésaurus en plus, seule @Marion-L1 peut dire

**Comment by lluc** [comment]
@Marion-L1 @bpradines  OK.
Donc : Ce champ peut être saisi pour chaque item ?
*je pose de nouveau la question, car chaque danse (thésaurus Danse) possède un champ de saisie libre ( le champ "notes")*

**Comment by Marion-L1** [comment]
Est-ce que cette question est urgente ? Il faudrait que je vérifie certaines informations auprès de Marlène... 
Puis-je répondre d'ici quelques jours ?
> @Marion-L1 @bpradines OK. Donc : Ce champ peut être saisi pour chaque item ? _je pose de nouveau la question, car chaque danse (thésaurus Danse) possède un champ de saisie libre ( le champ "notes")_

**Comment by lluc** [comment]
@Marion-L1  Oui, c'est pas à la minute même ... :wink:

**Comment by lluc** [comment]
@Marion-L1 As-tu pu voir cette question avec Marlène ? ...

**Comment by Marion-L1** [comment]
Malheureusement non. La question est posée mais Marlène a été en déplacements à plusieurs reprises.
Merci de relancer, je retourne à la recherche de cette réponse.

**Comment by Marion-L1** [comment]
@lluc Après discussion, même si ce champ était prévu à l'origine dans nos maquettes, vous pouvez en abandonner la création.
