### ISSUE TITLE
Champs additionnels en base de données - Ritournelle du conte

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#402]

**Comment by lluc** [comment]
@bpradines Ce champ existe déjà, il est dans l'onglet "Texte" de la saisie d'un item :thinking:

**Comment by bpradines** [comment]
> @bpradines Ce champ existe déjà, il est dans l'onglet "Texte" de la saisie d'un item 🤔

Quel est le nom de ce champ dans l'API (please) ?

**Comment by lluc** [comment]
@bpradines  Dans le *endpoint* de `/api/item/{id}`, il s'agit du champ **jingle**
