### ISSUE TITLE
Recherche rapide - Rechercher aussi dans les champs : mots-clés + résumés + paroles

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#403]
Recherche rapide :
- champs pris en compte actuellement : Titres + Informateurs·trices
- nouveau - faire la recherche aussi sur les champs : mots-clés + résumés + paroles

**Comment by bpradines** [comment]
@lluc quand je fais une recherche rapide sur "pas assez clair" (champ "Résumé") ou sur paroleparole (champ "Paroles"), le résultat trouvé s'affiche 2 fois !

**Comment by lluc** [comment]
> @lluc quand je fais une recherche rapide sur "pas assez clair" (champ "Résumé") ou sur paroleparole (champ "Paroles"), le résultat trouvé s'affiche 2 fois !

@bpradines Corrigé depuis par @fab2713

**Comment by bpradines** [comment]
Correction OK, Merci 👍
