### ISSUE TITLE
Recherche avancée - Icône (?) avec bulle d'aide au survol à la souris

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#407]
•	Dans l'onglet "Recherche avancée", à côté du titre "Recherche avancée", ajouter une icône ronde comportant un point d'interrogation. A survol (ou clic) de souris, afficher une bulle d'aide.
•	La bulle d'aide doit expliquer le fonctionnement général de la recherche avancée (entre autres : concept de ET/OU pas clair)

**Comment by lluc** [comment]
@bpradines  OK, mais il faudra nous fournir le petit texte d'aide.

**Comment by bpradines** [comment]
> @bpradines OK, mais il faudra nous fournir le petit texte d'aide.

Je vais te rédiger ça, et @Marion-L1 validera. Stay tuned ...

**Comment by bpradines** [comment]
Voici le texte pour la bulle d'aide au survol de l'icône (?) à placer à droite du titre "Recherche avancée" : 
[Francoralité - Texte bulle d'aide recherche avancée.md](https://github.com/Francoralite/francoralite/files/13486234/Francoralite.-.Texte.bulle.d.aide.recherche.avancee.md)

**Comment by bpradines** [comment]
> > Voici le texte pour la bulle d'aide au survol de l'icône (?) à placer à droite du titre "Recherche avancée" : [Francoralité - Texte bulle d'aide recherche avancée.md](https://github.com/Francoralite/francoralite/files/13486234/Francoralite.-.Texte.bulle.d.aide.recherche.avancee.md)
> 
> pour par **référence (cote)** : quand vous savez précisément l'enquête ou l'item que vous voulez, tapez son nom ou sa cote ; j'aurais même ajouté mission :
> 
> pour par **référence (cote)** : quand vous savez précisément la mission ou l'enquête ou l'item que vous voulez, tapez son nom ou sa cote ;

Effectivement on peut taper un id de mission, mais la recherche ne renvoie que des enquêtes (par défaut) ou des items ... 
On peut taper un peu ce qu'on veut mais on ne l'aura pas directement, seulement son contenu enquête ou items.
Du coup j'hésite à changer ça.

**Comment by bpradines** [comment]
@lluc suite à la demande de @Marion-L1 j'ai corrigé le texte qui apparaît dans la bulle d'aide affichée au survol de l'icône (?) dans la Recherche Avancée : 
[Francoralité - Texte bulle d'aide recherche avancée v2.md](https://github.com/Francoralite/francoralite/files/13987786/Francoralite.-.Texte.bulle.d.aide.recherche.avancee.v2.md)
Peux-tu mettre le texte à jour ?
