### ISSUE TITLE
Recherche rapide - Icône (?) avec bulle d'aide au survol à la souris

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#408]
A gauche du champ de saisie "Recherche rapide ...", afficher une icône ronde comportant un point d'interrogation.
A survol (ou clic) à la souris, afficher une bulle d'aide.
La bulle d'aide doit expliquer : les champs utilisés pour la recherche rapide

**Comment by lluc** [comment]
@bpradines OK, mais il faudra nous fournir le petit texte d'aide.
