### ISSUE TITLE
Recherches rapide et avancée - Afficher le nombre de résultats de chaque catégorie

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#411]
Ajouter l’affichage du nombre de résultats après Enquêtes et Items

**Comment by lluc** [comment]
@bpradines C'est  affiché, en haut à droite, en face la pagination. En attente  de déploiement sur la beta

**Comment by bpradines** [comment]
> @bpradines C'est affiché, en haut à droite, en face la pagination. En attente de déploiement sur la beta

OK j'irai voir, Merci :-)
