### ISSUE TITLE
Recherche avancée - Ordre des champs de recherche

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#413]
Ordre des champs de recherche : 
- Genre
- Incipit
- Texte
- Refrain
- Titre/référence Coirault
- Titre/référence Laforte
- Coupe
- Titre/référence de l’air/timbre

**Comment by fab2713** [comment]
@bpradines : Il y a beaucoup de champs dans la catégorie « genres » de la recherche avancée.
Ils sont affichés selon les types de domaines cochés, mais si l’on coche tous les domaines alors tous les champs sont affichés.
Serait-il possible de nous donner l’ordre d‘affichage pour l’ensemble ?
Voici la liste exhaustive des champs dans l’ordre actuel :
* Domaine(s) : Témoignage / Chanson / Autre expression vocale / Expression instrumentale / Conte ou récit légendaire
* Thématique(s) du témoignage
* Genre(s) de la chanson
* Timbre de l’air
* Timbre référencé
* Coupe(s)
* Genre(s) de l’autre expression vocale
* Titre référencé et cote Coirault
* Titre référencé et cote Laforte
* Genre(s) de l’expression instrumentale
* Voix/Instrument(s)
* Genre(s) du conte
* Texte
* Incipit
* Refrain
* Ritournelle

**Comment by Marion-L1** [comment]
Préférence d'ordre :

- Domaine(s) : Témoignage / Chanson / Autre expression vocale / Expression instrumentale / Conte ou récit légendaire
- Thématique(s) du témoignage
- Genre(s) du conte
- Ritournelle
- Genre(s) de l’expression instrumentale
- Genre(s) de l’autre expression vocale
- Genre(s) de la chanson
- Voix/Instrument(s)
- Texte
- Incipit
- Refrain
- Titre référencé et cote Coirault
- Titre référencé et cote Laforte
- Coupe(s)
- Timbre de l’air
- Timbre référencé
