### ISSUE TITLE
Recherche avancée - Thésaurus Coirault/Laforte - 1) Ajouter "Titre/Référence"

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#414]
Coirault/Laforte :
- ajouter « Titre/référence » pour Coirault, Laforte, Aarne-Thompson, Delarue-Thenèze, du timbre de l’air

**Comment by lluc** [comment]
@bpradines Désolé, on ne comprend pas bien la demande ... :thinking:

**Comment by bpradines** [comment]
> @bpradines Désolé, on ne comprend pas bien la demande ... 🤔

Voir avec Marion @Marion-L1 Help !!!

**Comment by Marion-L1** [comment]
Il existe plusieurs catalogues de référencement des chansons (Coirault et Laforte), ainsi que des contes (Aarne-Thompson et Delarue-Thénèze) et des mélodies (timbres). Pour chaque catalogue, il y a un nombre défini de possibilités  (mais qui peut quand même être important).

**Comment by Marion-L1** [comment]
Pour le moment, dans la recherche avancée et dans les fiches item, il y a la présence d'un champ "Coirault", qu'il faudrait renommer en "Titre/référence Coirault".
Il faudrait ajouter "Titre/référence Laforte" et "Titre/référence du timbre de l’air" dans la partie Chansons
ainsi que "Titre/référence Aarne-Thompson" et "Titre/référence Delarue-Thenèze" dans la partie Contes

**Comment by Marion-L1** [comment]
Je pense que les tickets #390 à #392 parlent de ça (catalogue Laforte) et #395 des contes

> Il existe plusieurs catalogues de référencement des chansons (Coirault et Laforte), ainsi que des contes (Aarne-Thompson et Delarue-Thénèze) et des mélodies (timbres). Pour chaque catalogue, il y a un nombre défini de possibilités (mais dont le nombre peut quand même être important). C'est ça que l'on aimerait voir apparaitre. Je sais que Michael travaillait sur l'intégration du catalogue Laforte à partir d'une liste déjà existante et libre de droits, mais je ne sais pas où il en était rendu dans ce travail.

**Comment by mnauge** [comment]
j'avais bien fait une intégration du premier tome de Laforte dans opentheso avec une navigation par 2 vue. Mais ce travail n'ai fait que pour le tome 1.  Selon moi, le plus simple est de repartir du tableur 
[Correspondances Coirault-Laforte.xlsx](https://github.com/Francoralite/francoralite/files/13451463/Correspondances.Coirault-Laforte.xlsx)

où on va retrouver le catalogue Laforte en regards du catalogue coirault. ça doit être facile de partir de ce fichier pour remplir le laforte sur francoralité

**Comment by fab2713** [comment]
je remets ce ticket en « à faire » dans l’attente des nouvelles structures de données

**Comment by Marion-L1** [comment]
Il me semble que ce ticket est clos. Cela concernait le nom du champ...et celui qui est présent actuellement est très bien.
