### ISSUE TITLE
Recherche avancée - Références - Remplacer l’intitulé « Description » par « Mots-clés »

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#417]

**Comment by lluc** [comment]
@bpradines Ne serait-ce pas un ajout plutôt qu'un remplacement ? :thinking:

**Comment by bpradines** [comment]
> @bpradines Ne serait-ce pas un ajout plutôt qu'un remplacement ? 🤔

Tu as raison, c'est un champ en plus.

**Comment by fab2713** [comment]
@bpradines Je pense qu’il s’agit donc d’un doublon avec le ticket #394, je propose d’y ajouter l’étiquette `duplicate` et de le clore, qu’en penses-tu ?

**Comment by bpradines** [comment]
@fab2713 effectivement c'est un doublon. En regardant le cahier des charges de Michael, j'ai vu qu'il a repris les demandes de plusieurs personnes et donc les doublons dans les demandes sont inévitables. Tu peux clore en duplicate.

**Comment by Marion-L1** [comment]
Dans l'onglet "Références" de la recherche avancée, on trouve toujours le champ "Description" que nous voulions voir transformé en "Mots-clés"

**Comment by fab2713** [comment]
@bpradines @Marion-L1
En référence au ticket https://github.com/Francoralite/francoralite/issues/418#issuecomment-1904027161, nous avons conservé le champ "Mots clés" dans la rubrique "Quoi ?".
Et vus les échanges ci-dessus, nous n’avons pas supprimé le champ "Description" et avions prévu de clore ce ticket. Est-ce que @bpradines tu confirmes la clôture ?

**Comment by bpradines** [comment]
@fab2713 @Marion-L1 Oui je confirme la clôture cart les deux colonnes Description et Mots-Clés existent dans les tableurs avec des données différentes donc il faut conserver les deux champs. Merci
