### ISSUE TITLE
Recherche avancée - Références - Que les recherches soient effectuées dans description et mots-clés

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#418]

**Comment by fab2713** [comment]
@bpradines Le champ de recherche sur la description est déjà dans le groupe des références, donc j’imagine qu’il y a rien à faire pour celui-ci. Ce ticket consiste-t-il simplement à y déplacer également le champ de recherche par mot-clé ? Si oui, quel est l’ordre souhaité pour ces champs ?

**Comment by bpradines** [comment]
@fab2713 je pense que le champ "Mots clés" est très bien dans "Quoi ?" et il n'y a pas lieu de le déplacer dans "Références". Tant que la recherche avancée marche sur les deux champs (et c'est le cas maintenant que les mots clés ont été ajoutés) c'est OK.

**Comment by bpradines** [comment]
@fab2713 donc c'est bon : si la recherche marche c'est OK
