### ISSUE TITLE
Ergonomie - Forme - Modif CSS globale du site (couleur marron-rouge à éclaircir)

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#425]
Poursuivre les améliorations d’ergonomies facilitant la lecture/interprétation humaine (réf. interne : usersFeedback.docx)

Couleurs : changer les couleurs pour les harmoniser avec le logo (le marron-rouge actuel fait trop ancien)

**Comment by fab2713** [comment]
@bpradines 
Après de nombreux essais d’éclaircissement du marron actuel qui ne s’avéraient ni très heureux ni très lisibles, je suis parti sur la réutilisation des couleurs du nouveau logo de Francoralité.
Et parmi ses couleurs, seul le thème à base de violet avait une lisibilité et un contraste suffisants sans être trop brillant pour les yeux.
Les autres couleurs du logo ont également été reprises telles quelles sur différents éléments (menu, liens, etc.).

Voici quelques exemples avec la page d’accueil et la recherche avancée :

![accueil](https://github.com/Francoralite/francoralite/assets/75579239/24374706-4fdb-491a-8d2d-8f149e47c681)

![recherche avancée](https://github.com/Francoralite/francoralite/assets/75579239/d1bab6b4-7653-41d6-aa74-cc45acb4f75f)

**Comment by bpradines** [comment]
Le contraste est meilleur qu'avant. Le thème plait à Marion. C'est OK pour moi.
