### ISSUE TITLE
[BUG] Recherche avancée - Saisie libre toujours possible si on tape plusieurs caractères trop vite alors qu'une valeur de liste est attendue

### ISSUE THREAD

**Issue by bpradines** [Francoralite/francoralite#432]
Dans un champ de saisie de la recherche avancée, où la sélection d'une valeur dans une liste multivaluée est attendue.

Si on tape très (trop) vite plusieurs caractères dans le champ (ex.: erererererere), la liste de valeurs prédéfinies n'a pas le temps de s'ouvrir, et si on clique à côté du champ, la valeur ne s'efface pas !

**Comment by fab2713** [comment]
Nous venons de tester ce problème sur la beta sur le premier champ (cote), mais nous n’arrivons pas à reproduire l’anomalie car lorsque l’on remplit avec n’importe quoi aucune suggestion ne s’affiche et en cliquant ailleurs le texte s’efface bien. De même, avec un vraie saisie, des suggestions sont affichées et en cliquant en dehors les suggestions disparaissent et la saisie s’efface.

Le problème que tu signales semble exister sur la prod, mais pas sur la beta.
Je pense que cela correspond à la correction suivante déjà déployée précédemment sur la beta : https://github.com/Francoralite/francoralite/commit/edafe481664fe143764959b383881ddf3baedc87

@bpradines Peux-tu nous indiquer sur quel champ tu rencontres ce problème et surtout s’il survient toujours de ton côté ?

**Comment by bpradines** [comment]
> Nous venons de tester ce problème sur la beta sur le premier champ (cote), mais nous n’arrivons pas à reproduire l’anomalie car lorsque l’on remplit avec n’importe quoi aucune suggestion ne s’affiche et en cliquant ailleurs le texte s’efface bien. De même, avec un vraie saisie, des suggestions sont affichées et en cliquant en dehors les suggestions disparaissent et la saisie s’efface.
> 
> Le problème que tu signales semble exister sur la prod, mais pas sur la beta. Je pense que cela correspond à la correction suivante déjà déployée précédemment sur la beta : [edafe48](https://github.com/Francoralite/francoralite/commit/edafe481664fe143764959b383881ddf3baedc87)
> 
> @bpradines Peux-tu nous indiquer sur quel champ tu rencontres ce problème et surtout s’il survient toujours de ton côté ?

Effectivement je n'arrive plus à reproduire le problème : j'ai dû confondre la bêta et la prod... Je m'en excuse, désolé.

**Comment by fab2713** [comment]
Pas de problème, je mets ce ticket avec ceux déployés. :wink:
