### ISSUE TITLE
Bouton ANNULER : ne fonctionne pas

### ISSUE THREAD

**Issue by Alexandre-S1** [Francoralite/francoralite#59]
Bouton "Annuler" provoque seulement une remontée en haut de page.
Par exemple ici en création d'enquête :https://app-francoralite-test.huma-num.fr/institution/1/fond/4/mission/7/collection/add#

**Comment by lluc** [comment]
@Alexandre-S1 Bizarre, depuis mon navigateur, cela fonctionne ...

**Comment by Alexandre-S1** [comment]
Test effectués sur Firefox + Waterfox + Opera

**Comment by lluc** [comment]
@Alexandre-S1 Effectué aussi sur Firefox.  :-(

**Comment by Alexandre-S1** [comment]
Etrange : le bouton annuler vient de me renvoyer sur cette page GitHub : comme s'il avait une fonction de "retour à la page précédente"...

**Comment by lluc** [comment]
@Alexandre-S1 de même. => je revois le mécanisme de pages précédentes.

**Comment by lluc** [comment]
A vérifier.

**Comment by lluc** [comment]
Le fonctionnement est correct.
