### ISSUE TITLE
Item - l'onglet Texte se vide automatiquement en édition

### ISSUE THREAD

**Issue by Alexandre-S1** [Francoralite/francoralite#66]
Lorsqu'on clique sur le champ vide, les annotations précédemment rentrées apparaissent à nouveau.

**Comment by lluc** [comment]
@Alexandre-S1 les données semblent être toujours présentes dans la base de données : elle s'affichent dès que l'on clique sur une des zones de saisie de texte de cet onglet.  
Je vais regarder plus précisémment ce qui pose ses problèmes d'affichage.

**Comment by lluc** [comment]
@Alexandre-S1 visiblement c'est un bug référencé du composant que j'utilise :
- https://github.com/json-editor/json-editor/issues/574
- https://github.com/sparksuite/simplemde-markdown-editor/issues/344
- https://github.com/sparksuite/simplemde-markdown-editor/issues/596

**Comment by lluc** [comment]
@Alexandre-S1 ... quasi insoluble, pour le moment. :-(

**Comment by lluc** [comment]
@Alexandre-S1 ... quasi insoluble, pour le moment. :-(
