### ISSUE TITLE
FONDS - On peut donner la même cote à 2 fonds différents.

### ISSUE THREAD

**Issue by Alexandre-S1** [Francoralite/francoralite#87]

**Comment by mnauge** [comment]
Effectivement plus possible.  Mais aucune information de précise pourquoi le fonds n'a pas pu etre crée... Peut etre le cloturer et ajouter une issue coté ergonomie ?!

**Comment by mnauge** [comment]
Cet ajout empêche la modification (MAJ) des fonds... A retravailler

**Comment by lluc** [comment]
Ce problème est résolu.
