### ISSUE TITLE
ITEM - Consultation - Le player mouline

### ISSUE THREAD

**Issue by Alexandre-S1** [Francoralite/francoralite#94]
ITEM - Consultation
- Le player mouline sans fonctionner, reste sur "Chargement..." (testé avec Firefox, Opera, Vivaldi, Safari, Waterfox)

**Comment by mnauge** [comment]
Pareil pour moi

**Comment by lluc** [comment]
@mnauge @Alexandre-S1 êtes-vous certains que les fichiers sont format MP3 ? ;-)

**Comment by mnauge** [comment]
@lluc je viens de tester avec un mp3, c'est le même problème.

**Comment by mnauge** [comment]
false because not superuser ?!
si ça peut servir :

           loadPlayer('https://app.preprod.francoralite.net/api/timeside/6/analyze',
             "https://app.preprod.francoralite.net/api/item/6/download/UPOI_AFE_0000_0001_000.mp3",
             undefined, '6', visualizers,
             CURRENT_USER_NAME,
             false); //false because not superuser

**Comment by lluc** [comment]
@mnauge Il semblerait que ce soit dû à un problème de déploiement.  
En l'occurence, les bibliothèques Javascript tiers de Timeside ne semblent pas être présentes.  
J'en parle rapidement avec @achaussier

**Comment by mnauge** [comment]
Le player peut maintenant jouer un son et nous pouvons utiliser les markers. Reste un problème d'affichage du spectro... Je vais tagger ça en ergo.
